[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  included_files = ["lib/**", "models/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

